#!/bin/sh
set -e

if [ -x "/etc/init.d/dragent" ]; then
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d dragent stop || exit $?
        else
                /etc/init.d/dragent stop || exit $?
        fi
fi

DKMS_PACKAGE_NAME="draios"
DKMS_VERSION="0.1.1"

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_PACKAGE_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_PACKAGE_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
