--[[
Copyright (C) 2013-2018 Draios Inc dba Sysdig.

This file is part of sysdig.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

--]]

view_info = 
{
	id = "ct_sourceips",
	name = "Source IPs",
	description = "Show the IP addresses generating AWS events and the number of events each IP has generated.",
	tips = {"Drill down to see what type of events were generated by one of the IPs."},
	tags = {"csysdig-aws"},
	view_type = "table",
	applies_to = {"", "ct.name", "ct.shortsrc", "ct.useragent", "ct.region", "s3.uri", "s3.bucket"},
	is_root = false,
	drilldown_target = "ct_sources",
	use_defaults = false,
	columns = 
	{
		{
			name = "NA",
			field = "ct.srcip",
			is_key = true
		},
		{
			name = "CLIENT IP",
			description = "The client IP address.",
			field = "ct.srcip",
			colsize = 32,
		},
		{
			name = "EVT COUNT",
			field = "evt.count",
			description = "The number of events the generated from the IP address.",
			colsize = 12,
			aggregation = "SUM",
			is_sorting = true,
		},
	},
}
