--[[
Copyright (C) 2013-2018 Draios Inc dba Sysdig.

This file is part of sysdig.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

--]]

view_info = 
{
	id = "ct_useragents",
	name = "User Agents",
	description = "Show the different client user agents and the number of events generated by each of them.",
	tips = {"Drill down to see what type of events a user agent has generated."},
	tags = {"csysdig-aws"},
	view_type = "table",
	applies_to = {"", "ct.name", "ct.shortsrc", "ct.region", "ct.srcip", "s3.uri", "s3.bucket"},
	is_root = false,
	drilldown_target = "ct_sources",
	use_defaults = false,
	columns = 
	{
		{
			name = "NA",
			field = "ct.useragent",
			is_key = true
		},
		{
			name = "EVT COUNT",
			field = "evt.count",
			description = "The number of events the user agent has generated.",
			colsize = 12,
			aggregation = "SUM",
			is_sorting = true,
		},
		{
			name = "AGENT",
			description = "The user agent generating activity.",
			field = "ct.useragent",
			colsize = 640,
		},
	},
}
