FROM fedora:27

RUN yum -y install \
	wget \
	git \
	gcc \
	gcc-c++ \
	autoconf \
	bison \
	flex \
	make \
	cmake \
	elfutils-devel \
	findutils \
	kmod \
	python-lxml && yum clean all

ADD builder-entrypoint.sh /
WORKDIR /build/probe
ENTRYPOINT [ "/builder-entrypoint.sh" ]
