name: Builder update
on:
  push:
    branches: [s390x-ga]
    paths: ['docker/builder/**']

jobs:
  update-builder:
    env:
      REGISTRY: ghcr.io
      BUILDER_IMAGE_BASE: ghcr.io/draios/sysdig-builder
      SKEL_BUILDER_IMAGE_BASE: ghcr.io/draios/sysdig-skel-builder

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sysdig
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'amd64,arm64,s390x'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build new skeleton builder
        id: build-skeleton-builder
        uses: docker/build-push-action@v3
        with:
          context: docker/builder
          file:  docker/builder/modern_bpf_probe.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/s390x
          tags: ${{ format('{0}:dev,{0}:{1}', env.SKEL_BUILDER_IMAGE_BASE, github.sha) }}
          push: true
      
      - name: Build new builder
        id: build-builder
        uses: docker/build-push-action@v3
        with:
          context: docker/builder
          platforms: linux/amd64,linux/arm64,linux/s390x
          tags: ${{ format('{0}:dev,{0}:{1}', env.BUILDER_IMAGE_BASE, github.sha) }}
          push: true
